title: Gitesh Deshmukh
logo: https://github.com/gitesh21/My-Portfolio/blob/main/Screenshot%202024-06-04%20at%2001.17.10.png?raw=true
#description: text below image
#show_downloads: true
theme: jekyll-theme-minimal
